---
- name: check connectivity
  ping:
    data: alive


- name: update repos
  apt:
    update_cache: yes
    allow_downgrade: yes

- name: Unhold kubeadm for updating
  dpkg_selections:
    name: kubeadm
    selection: install


- name: Update kubeadm version
  apt:
    name: kubeadm={{ upgrade_kubeadm_version }}
    state: present


- name: Hold the packages to prevent accidental updates
  dpkg_selections:
    name: kubeadm
    selection: hold


- name: Upgrade kubeadm on master node
  shell:
    cmd: kubeadm upgrade node --dry-run
  register: upgrade_master_result


- name: Echo the result of upgrade kubeadm
  debug:
    var: upgrade_master_result


- name: Check to proceed to upgrade master nodes
  pause:
    prompt: "Proceed if everything is alright"

- name: Upgrade kubeadm on master node
  shell:
    cmd: kubeadm upgrade node --dry-run
  register: actual_upgrade_master_result

- name: Echo the result of actual upgrade kubeadm
  debug:
    var: actual_upgrade_master_result

