---
- name: check connectivity
  ping:
    data: alive


- name: update repos
  apt:
    update_cache: yes
    allow_downgrade: yes

- name: Unhold kubeadm for updating
  dpkg_selections:
    name: kubeadm
    selection: install


- name: Update kubeadm version
  apt:
    name: kubeadm={{ upgrade_kubeadm_version }}
    state: present



- name: Hold the packages to prevent accidental updates
  dpkg_selections:
    name: kubeadm
    selection: hold


- name: Verify if the upgrade is compatible with the current cluster configuration
  shell:
    cmd: kubeadm upgrade node --dry-run
  register: dry_run_upgrade


- name: Print the result of upgrade apply command
  debug:
    var: dry_run_upgrade


- name: Check to proceed to upgrade master nodes
  pause:
    prompt: "Proceed if everything is alright"


- name: Upgrade the cluster
  shell:
    cmd: kubeadm upgrade node
  register: cluster_upgrade


- name: Print the result of upgrade apply command
  debug:
    var: cluster_upgrade


- name: Check to proceed to upgrade master nodes
  pause:
    prompt: "Proceed if everything is alright"


